import { QueryOutput } from './QueryOutput';
import { feature_QueryOutput } from './feature_QueryOutput';

/*
 * Selected/partial export of MapsEngine REST API.
 *
 * Generated by https://www.npmjs.com/package/openapi-typescript-codegen.
 */

export type * from './Crs';
export type * from './feature_QueryOutput';
export type * from './geo_Bounds';
export type * from './geo_Crs';
export type * from './geo_Extent';
export type * from './geo_Geometry'
export type * from './geo_json_LineString';
export type * from './geo_json_MultiLineString';
export type * from './geo_json_MultiPoint';
export type * from './geo_json_MultiPolygon';
export type * from './geo_json_Point';
export type * from './geo_json_Polygon';
export type { query_FeatureRef } from './query_FeatureRef';
export type * from './ModelRef';
export type * from './QueryOutput';

 /**
  * Search for feature(s).
  * Search for feature(s).
  * @param requestBody Query to match features to be retrieved.
  * @returns any List of features.
  * @throws ApiError
  */
export type searchFeatures_Output = QueryOutput & {
  data?: Array<QueryOutput & {
    data: Array<feature_QueryOutput>;
  }>;
};
